export const categories = ['Scotch', 'Bourbon', 'Irish', 'Canadian', 'Japanese'] as const;
export type Category = (typeof categories)[number] & string;

export type whisky = {
  name: string;
  price: number;
  category: Category;
  rating: number;
  imgPath: `/${string}.png`;
};

export const whiskies: whisky[] = [
  {
    name: 'ABERFELDY - 12 YEAR OLD',
    price: 69.99,
    category: 'Scotch',
    rating: 3.9,
    imgPath: '/scotch/aberfeldy.png',
  },
  {
    name: 'ARDBEG - 10 YEAR OLD',
    price: 112.99,
    category: 'Scotch',
    rating: 4.3,
    imgPath: '/scotch/ardbeg.png',
  },
  {
    name: 'BOWMORE - 12 YEAR OLD',
    price: 69.99,
    category: 'Scotch',
    rating: 3.7,
    imgPath: '/scotch/bowmore.png',
  },
  {
    name: 'BRUICHLADDICH - SCOTTISH BARLEY THE LADDIE CLASSIC',
    price: 85.99,
    category: 'Scotch',
    rating: 3.9,
    imgPath: '/scotch/bruichladdich.png',
  },
  {
    name: 'DALMORE - 12 YEAR OLD',
    price: 114.99,
    category: 'Scotch',
    rating: 4.0,
    imgPath: '/scotch/dalmore.png',
  },
  {
    name: 'GLENFIDDICH SPECIAL RESERVE - 12 YEAR OLD',
    price: 73.99,
    category: 'Scotch',
    rating: 3.7,
    imgPath: '/scotch/glenfiddich.png',
  },
  {
    name: 'GLENLIVET - 12 YEAR OLD',
    price: 75.99,
    category: 'Scotch',
    rating: 3.6,
    imgPath: '/scotch/glenlivet.png',
  },
  {
    name: 'GLENMORANGIE - 10 YEAR OLD THE categoryAL',
    price: 74.99,
    category: 'Scotch',
    rating: 4.1,
    imgPath: '/scotch/glenmorangie.png',
  },
  {
    name: 'HIGHLAND PARK - 12 YEAR OLD',
    price: 79.99,
    category: 'Scotch',
    rating: 4.1,
    imgPath: '/scotch/highland-park.png',
  },
  {
    name: 'LAGAVULIN - 8 YEAR OLD',
    price: 99.99,
    category: 'Scotch',
    rating: 4.1,
    imgPath: '/scotch/lagavulin.png',
  },
  {
    name: 'LAPHROAIG - 10 YEAR OLD',
    price: 84.99,
    category: 'Scotch',
    rating: 4.3,
    imgPath: '/scotch/laphroaig.png',
  },
  {
    name: 'MACALLAN - SHERRY OAK 12 YEAR OLD',
    price: 174.99,
    category: 'Scotch',
    rating: 4.4,
    imgPath: '/scotch/macallan.png',
  },
  {
    name: 'TALISKER - 10 YEAR OLD',
    price: 119.99,
    category: 'Scotch',
    rating: 4.4,
    imgPath: '/scotch/talisker.png',
  },
  {
    name: "BALLANTINE'S - FINEST",
    price: 29.99,
    category: 'Scotch',
    rating: 3,
    imgPath: '/scotch-blended/ballantines.png',
  },
  {
    name: 'CHIVAS REGAL - 12 YEAR OLD',
    price: 60.99,
    category: 'Scotch',
    rating: 3.2,
    imgPath: '/scotch-blended/chivas-regal.png',
  },
  {
    name: 'CUTTY SARK',
    price: 27.99,
    category: 'Scotch',
    rating: 3.3,
    imgPath: '/scotch-blended/cutty-sark.png',
  },
  {
    name: "DEWAR'S - WHITE LABEL",
    price: 27.49,
    category: 'Scotch',
    rating: 3.8,
    imgPath: '/scotch-blended/dewars.png',
  },
  {
    name: "GRANT'S - TRIPLE WOOD",
    price: 28.99,
    category: 'Scotch',
    rating: 3.2,
    imgPath: '/scotch-blended/grants.png',
  },
  {
    name: 'JOHNNIE WALKER - 12 YEAR OLD BLACK LABEL',
    price: 63.99,
    category: 'Scotch',
    rating: 3.8,
    imgPath: '/scotch-blended/johnnie-walker-black.png',
  },
  {
    name: 'JOHNNIE WALKER - RED LABEL',
    price: 31.99,
    category: 'Scotch',
    rating: 2.9,
    imgPath: '/scotch-blended/johnnie-walker-red.png',
  },
  {
    name: 'MATTHEW GLOAG - THE FAMOUS GROUSE',
    price: 28.99,
    category: 'Scotch',
    rating: 3.8,
    imgPath: '/scotch-blended/famous-grouse.png',
  },
  {
    name: "BOOKER'S - BOURBON SMALL BATCH",
    price: 135.99,
    category: 'Bourbon',
    rating: 4.2,
    imgPath: '/bourbon/bookers.png',
  },
  {
    name: "JACK DANIEL'S - OLD 7",
    price: 37.49,
    category: 'Bourbon',
    rating: 3.7,
    imgPath: '/bourbon/jack-daniels.png',
  },
  {
    name: 'BULLEIT - FRONTIER BOURBON',
    price: 44.99,
    category: 'Bourbon',
    rating: 3.9,
    imgPath: '/bourbon/bulleit.png',
  },
  {
    name: 'JIM BEAM - KENTUCKY BOURBON',
    price: 31.99,
    category: 'Bourbon',
    rating: 3.5,
    imgPath: '/bourbon/jim-beam.png',
  },
  {
    name: 'KNOB CREEK - 9 YEAR OLD BOURBON SMALL BATCH',
    price: 53.99,
    category: 'Bourbon',
    rating: 4.1,
    imgPath: '/bourbon/knob-creek.png',
  },
  {
    name: "MAKER'S MARK - KENTUCKY BOURBON",
    price: 46.99,
    category: 'Bourbon',
    rating: 4.0,
    imgPath: '/bourbon/makers-mark.png',
  },
  {
    name: 'OLD FORESTER - 1920 WHISKEY ROW SERIES',
    price: 92.99,
    category: 'Bourbon',
    rating: 4.2,
    imgPath: '/bourbon/old-forester.png',
  },
  {
    name: 'RABBIT HOLE - CAVEHILL',
    price: 77.99,
    category: 'Bourbon',
    rating: 4.4,
    imgPath: '/bourbon/rabbit-hole.png',
  },
  {
    name: 'WILD TURKEY - 81 PROOF',
    price: 32.99,
    category: 'Bourbon',
    rating: 3.6,
    imgPath: '/bourbon/wild-turkey.png',
  },
  {
    name: 'WOODFORD RESERVE - DISTILLERS SELECT',
    price: 53.99,
    category: 'Bourbon',
    rating: 4.3,
    imgPath: '/bourbon/woodford-reserve.png',
  },
  {
    name: 'BUSHMILLS - BLACK BUSH',
    price: 40.49,
    category: 'Irish',
    rating: 4.2,
    imgPath: '/irish/bushmills.png',
  },
  {
    name: 'GLENDALOUGH - DOUBLE BARREL',
    price: 49.99,
    category: 'Irish',
    rating: 4.2,
    imgPath: '/irish/glendalough.png',
  },
  {
    name: 'JAMESON - IRISH',
    price: 38.49,
    category: 'Irish',
    rating: 4.1,
    imgPath: '/irish/jameson.png',
  },
  {
    name: 'TULLAMORE DEW',
    price: 39.99,
    category: 'Irish',
    rating: 3.8,
    imgPath: '/irish/tullamore.png',
  },
  {
    name: 'ALBERTA PREMIUM - CANADIAN RYE',
    price: 22.99,
    category: 'Canadian',
    rating: 4.1,
    imgPath: '/canadian/alberta-premium.png',
  },
  {
    name: 'CANADIAN CLUB - PREMIUM',
    price: 23.49,
    category: 'Canadian',
    rating: 3.7,
    imgPath: '/canadian/canadian-club.png',
  },
  {
    name: "CANADIAN CLUB - 100% RYE CHAIRMAN'S SELECT",
    price: 24.99,
    category: 'Canadian',
    rating: 4.0,
    imgPath: '/canadian/canadian-club-100-rye.png',
  },
  {
    name: 'CROWN ROYAL',
    price: 28.99,
    category: 'Canadian',
    rating: 3.6,
    imgPath: '/canadian/crown-royal.png',
  },
  {
    name: 'FORTY CREEK - BARREL SELECT',
    price: 27.49,
    category: 'Canadian',
    rating: 4.2,
    imgPath: '/canadian/forty-creek.png',
  },
  {
    name: 'REIFEL RYE - CANADIAN WHISKY',
    price: 43.99,
    category: 'Canadian',
    rating: 4.2,
    imgPath: '/canadian/reifel-rye.png',
  },
  {
    name: "J. P. WISER'S DELUXE",
    price: 25.49,
    category: 'Canadian',
    rating: 3.6,
    imgPath: '/canadian/wisers.png',
  },
  {
    name: 'AKASHI JAPANESE BLENDED WHISKY',
    price: 70.99,
    category: 'Japanese',
    rating: 4.2,
    imgPath: '/japanese/akashi.png',
  },
  {
    name: 'SUNTORY - WORLD WHISKY AO',
    price: 99.99,
    category: 'Japanese',
    rating: 4,
    imgPath: '/japanese/ao.png',
  },
  {
    name: 'SUNTORY WHISKY - HIBIKI JAPANESE HARMONY',
    price: 161.99,
    category: 'Japanese',
    rating: 4.2,
    imgPath: '/japanese/hibiki.png',
  },
  {
    name: 'NIKKA - TAKETSURU PURE MALT',
    price: 88.99,
    category: 'Japanese',
    rating: 4.7,
    imgPath: '/japanese/taketsuru.png',
  },
  {
    name: 'NIKKA - YOICHI SINGLE MALT',
    price: 94.99,
    category: 'Japanese',
    rating: 4.5,
    imgPath: '/japanese/yoichi.png',
  },
];
